//------------------------------------------------------------------------------
// This code was generated by a tool.
//
//   Tool : MetaMask Unity SDK ABI Code Generator
//   Input filename:  .sol
//   Output filename: champs3Hero.Attr.cs
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// <auto-generated />
//------------------------------------------------------------------------------

#if MetamaskPlugin 


using System;
using System.Numerics;
using System.Threading.Tasks;
using evm.net;
using evm.net.Models;

namespace RunHeroContract
{
	public class Attr
	{
		[EvmParameterInfo(Name = "rarity", Type = "uint256")]
		public BigInteger rarity;
		
		[EvmParameterInfo(Name = "level", Type = "uint256")]
		public BigInteger level;
		
		[EvmParameterInfo(Name = "talent", Type = "uint256")]
		public BigInteger talent;
		
		[EvmParameterInfo(Name = "runningSpeed", Type = "uint256")]
		public BigInteger runningSpeed;
		
		[EvmParameterInfo(Name = "swimmingSpeed", Type = "uint256")]
		public BigInteger swimmingSpeed;
		
		[EvmParameterInfo(Name = "climbingSpeed", Type = "uint256")]
		public BigInteger climbingSpeed;
		
		[EvmParameterInfo(Name = "flightSpeed", Type = "uint256")]
		public BigInteger flightSpeed;
		
		[EvmParameterInfo(Name = "energy", Type = "uint256")]
		public BigInteger energy;
		
	}
}
#endif